### ISSUE TITLE
First of All Nice One!

### ISSUE THREAD

**Issue by frank-dspeed** [signicode/rw-stream#1]
I am Frank Lemanschik Senior Lead Engineer and i Love your work not my CodeStyle but i love it i will integrate your algo in my Stream Lib Voted you up on stackoverflow and will Create a PR for the Missing Flow Control Part aka Note in your readme so that this writes only if it got read already :dancing_men: 

cze bro!

**Comment by MichalCz** [comment]
Thanks. :)
